ALTER TABLE application_chat
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE application_chat_record
    ADD COLUMN IF NOT EXISTS vote_other_content VARCHAR(1024) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS vote_reason VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source JSONB NOT NULL DEFAULT '{}'::jsonb;