spring:
  datasource:
    url: jdbc:postgresql://172.22.214.85:5432/MaxKB4j
    username: tarzan_postgres
    password: ycn4NRhjN2
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://tarzan_mongo:ycn4NRhjN2@172.22.214.85:27017/MaxKB4j?authSource=admin

