package com.tarzan.maxkb4j.module.system.user.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Getter
public enum ResourcePermissionEnum {


    APPLICATION_CREATE("APPLICATION","APPLICATION","READ+CREATE", "MANAGE"),
    APPLICATION_EDIT("APPLICATION","APPLICATION","READ+EDIT", "MANAGE"),
    APPLICATION_DELETE("APPLICATION","APPLICATION","READ+DELETE", "MANAGE"),
    APPLICATION_READ("APPLICATION","APPLICATION","READ", "VIEW"),
    APPLICATION_EXPORT("APPLICATION","APPLICATION","READ+EXPORT", "MANAGE"),
    APPLICATION_IMPORT("KNOWLEDGE","KNOWLEDGE","READ+IMPORT", "MANAGE"),

    APPLICATION_OVERVIEW_PUBLIC_ACCESS("APPLICATION","APPLICATION_OVERVIEW","READ+PUBLIC_ACCESS", "MANAGE"),
    APPLICATION_OVERVIEW_ACCESS("APPLICATION","APPLICATION_OVERVIEW","READ+ACCESS", "MANAGE"),
    APPLICATION_OVERVIEW_EMBED("APPLICATION","APPLICATION_OVERVIEW","READ+EMBED", "MANAGE"),
    APPLICATION_OVERVIEW_API_KEY("APPLICATION","APPLICATION_OVERVIEW","READ+API_KEY", "MANAGE"),
    APPLICATION_OVERVIEW_DISPLAY("APPLICATION","APPLICATION_OVERVIEW","READ+DISPLAY", "MANAGE"),
    APPLICATION_OVERVIEW_READ("APPLICATION","APPLICATION_OVERVIEW","READ", "VIEW"),

    APPLICATION_CHAT_LOG_ADD_KNOWLEDGE("APPLICATION","APPLICATION_CHAT_LOG","READ+ADD_KNOWLEDGE", "MANAGE"),
    APPLICATION_CHAT_LOG_CLEAR_POLICY("APPLICATION","APPLICATION_CHAT_LOG","READ+CLEAR_POLICY", "MANAGE"),
    APPLICATION_CHAT_LOG_ANNOTATION("APPLICATION","APPLICATION_CHAT_LOG","READ+ANNOTATION", "MANAGE"),
    APPLICATION_CHAT_LOG_EXPORT("APPLICATION","APPLICATION_CHAT_LOG","READ+EXPORT", "MANAGE"),
    APPLICATION_CHAT_LOG_READ("APPLICATION","APPLICATION_CHAT_LOG","READ", "VIEW"),

    APPLICATION_ACCESS_READ("APPLICATION","APPLICATION_ACCESS","READ", "MANAGE"),

    KNOWLEDGE_CREATE("KNOWLEDGE","KNOWLEDGE","READ+CREATE", "MANAGE"),
    KNOWLEDGE_EDIT("KNOWLEDGE","KNOWLEDGE","READ+EDIT", "MANAGE"),
    KNOWLEDGE_DELETE("KNOWLEDGE","KNOWLEDGE","READ+DELETE", "MANAGE"),
    KNOWLEDGE_READ("KNOWLEDGE","KNOWLEDGE","READ", "VIEW"),
    KNOWLEDGE_EXPORT("KNOWLEDGE","KNOWLEDGE","READ+EXPORT", "MANAGE"),
    KNOWLEDGE_VECTOR("KNOWLEDGE","KNOWLEDGE","READ+VECTOR", "MANAGE"),
    KNOWLEDGE_GENERATE("KNOWLEDGE","KNOWLEDGE","READ+GENERATE", "MANAGE"),
    KNOWLEDGE_SYNC("KNOWLEDGE","KNOWLEDGE","READ+SYNC", "MANAGE"),

    KNOWLEDGE_DOCUMENT_CREATE("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+CREATE", "MANAGE"),
    KNOWLEDGE_DOCUMENT_EDIT("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+EDIT", "MANAGE"),
    KNOWLEDGE_DOCUMENT_DELETE("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+DELETE", "MANAGE"),
    KNOWLEDGE_DOCUMENT_VECTOR("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+VECTOR", "MANAGE"),
    KNOWLEDGE_DOCUMENT_GENERATE("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+GENERATE", "MANAGE"),
    KNOWLEDGE_DOCUMENT_SYNC("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+SYNC", "MANAGE"),
    KNOWLEDGE_DOCUMENT_MIGRATE("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+MIGRATE", "MANAGE"),
    KNOWLEDGE_DOCUMENT_DOWNLOAD("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+DOWNLOAD", "MANAGE"),
    KNOWLEDGE_DOCUMENT_EXPORT("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ+EXPORT", "MANAGE"),
    KNOWLEDGE_DOCUMENT_READ("KNOWLEDGE","KNOWLEDGE_DOCUMENT","READ", "VIEW"),

    KNOWLEDGE_HIT_TEST_READ("KNOWLEDGE","KNOWLEDGE_HIT_TEST","READ", "VIEW"),

    KNOWLEDGE_PROBLEM_CREATE("KNOWLEDGE","KNOWLEDGE_PROBLEM","READ+CREATE", "MANAGE"),
    KNOWLEDGE_PROBLEM_EDIT("KNOWLEDGE","KNOWLEDGE_PROBLEM","READ+EDIT", "MANAGE"),
    KNOWLEDGE_PROBLEM_DELETE("KNOWLEDGE","KNOWLEDGE_PROBLEM","READ+DELETE", "MANAGE"),
    KNOWLEDGE_PROBLEM_RELATE("KNOWLEDGE","KNOWLEDGE_PROBLEM","READ+RELATE", "MANAGE"),
    KNOWLEDGE_PROBLEM_READ("KNOWLEDGE","KNOWLEDGE_PROBLEM","READ", "VIEW"),

    TOOL_CREATE("TOOL","TOOL","READ+CREATE", "MANAGE"),
    TOOL_EDIT("TOOL","TOOL","READ+EDIT", "MANAGE"),
    TOOL_DELETE("TOOL","TOOL","READ+DELETE", "MANAGE"),
    TOOL_READ("TOOL","TOOL","READ", "VIEW"),
    TOOL_IMPORT("TOOL","TOOL","READ+IMPORT", "MANAGE"),
    TOOL_EXPORT("TOOL","TOOL","READ+EXPORT", "MANAGE"),

    MODEL_CREATE("MODEL","MODEL","READ+CREATE", "MANAGE"),
    MODEL_EDIT("MODEL","MODEL","READ+EDIT", "MANAGE"),
    MODEL_DELETE("MODEL","MODEL","READ+DELETE", "MANAGE"),
    MODEL_READ("MODEL","MODEL","READ", "VIEW"),
    ;

    private final String group;
    private final String resource;
    private final String operate;
    private final String permission;

    ResourcePermissionEnum(String group,String resource, String operate, String permission) {
        this.group = group;
        this.resource = resource;
        this.operate = operate;
        this.permission = permission;
    }


    public static List<ResourcePermissionEnum> getPermissions(String group) {
        return Arrays.stream(values()).filter(e-> e.group.equals(group))
                .collect(Collectors.toList());
    }
}
